[build]
  base = "AdminPannel"
  publish = "dist"       # <-- relative to base
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "22"
  VITE_API_URL = "https://drrahulsingh-website.onrender.com"
